apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-app
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: mlops-app
  template:
    metadata:
      labels:
        app: mlops-app
    spec:
      containers:
      - name: mlops-app
        image: us-central1-docker.pkg.dev/project-1680e564-23e9-4e9c-b2b/my-repo/mlops-app:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"  # Réduit de 512Mi
            cpu: "250m"      # Réduit de 500m
          limits:
            memory: "512Mi"  # Réduit de 1Gi
            cpu: "500m"      # Réduit de 1000m
---
apiVersion: v1
kind: Service
metadata:
  name: mlops-service
spec:
  selector:
    app: mlops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer